language: python
python:
#- 3.5
- 3.6
- 3.7
- 3.8
before_install: # see https://gist.github.com/qoomon/c57b0dc866221d91704ffef25d41adcf
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval $(ssh-agent -s)
- ssh-add deploy_key
- sudo apt-get update
- sudo apt-get install libopenblas-dev libfftw3-dev
install:
- pip install setuptools
- python -m pip install --upgrade -r requirements.txt --no-binary setuptools_scm
- python setup.py install
script:
- python -m pytest --verbose --full-trace -s; # TODO: flake8 back
notifications:
  email:
  - antoine.sanner@imtek.uni-freiburg.de

