language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - source .travis.before_install.bash
install:
  - pip install setuptools
  - python -m pip install --upgrade -r requirements.txt --no-binary setuptools_scm
  - python setup.py install
script:
  - python -m pytest --flake8 --verbose --full-trace -s;
notifications:
  email:
    - antoine.sanner@imtek.uni-freiburg.de
