language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
- ssh-add deploy_key
install:
- pip install setuptools
- python -m pip install --upgrade -r requirements.txt --no-binary setuptools_scm
- python setup.py install
script:
- python -m pytest --flake8 --verbose --full-trace -s;
notifications:
  email:
  - antoine.sanner@imtek.uni-freiburg.de

